# Generated by Django 3.2.5 on 2021-07-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_block', models.IntegerField(default=0)),
                ('hash_block', models.CharField(max_length=400)),
                ('time_block', models.DateTimeField(verbose_name='block time')),
                ('mine_adress', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
