# Generated by Django 3.2.5 on 2021-07-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcsChain', '0002_auto_20210719_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='mine_adress',
            new_name='miner_adress',
        ),
    ]
